function( install_extlibs EXTLIBS_DIR INSTALL_DIR )
	set( CMAKE_FILES 
			"${EXTLIBS_DIR}/cmake/FindGLEW.cmake"
			"${EXTLIBS_DIR}/cmake/FindSDL2.cmake"
			"${EXTLIBS_DIR}/cmake/FindTMXLite.cmake" )

	install( FILES ${CMAKE_FILES} DESTINATION ${INSTALL_DIR}/CMake )
	install( DIRECTORY ${EXTLIBS_DIR}/GLEW DESTINATION ${INSTALL_DIR} )
	install( DIRECTORY ${EXTLIBS_DIR}/SDL2 DESTINATION ${INSTALL_DIR} )
	install( DIRECTORY ${EXTLIBS_DIR}/TMXLite DESTINATION ${INSTALL_DIR} )
endfunction()